// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Migo_be
{
    public partial class TrainingsML
    {
        /// <summary>
        /// model input class for TrainingsML.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Quality")]
            public string Quality { get; set; }

            [ColumnName(@"Efficiency")]
            public string Efficiency { get; set; }

            [ColumnName(@"Agility")]
            public string Agility { get; set; }

            [ColumnName(@"Innovation")]
            public string Innovation { get; set; }

            [ColumnName(@"Integrity")]
            public string Integrity { get; set; }

            [ColumnName(@"Functional Components")]
            public string Functional_Components { get; set; }

            [ColumnName(@"Performance")]
            public string Performance { get; set; }

            [ColumnName(@"Result [Training Tag]")]
            public float Result__Training_Tag_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TrainingsML.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Quality")]
            public float[] Quality { get; set; }

            [ColumnName(@"Efficiency")]
            public float[] Efficiency { get; set; }

            [ColumnName(@"Agility")]
            public float[] Agility { get; set; }

            [ColumnName(@"Innovation")]
            public float[] Innovation { get; set; }

            [ColumnName(@"Integrity")]
            public float[] Integrity { get; set; }

            [ColumnName(@"Functional Components")]
            public float[] Functional_Components { get; set; }

            [ColumnName(@"Performance")]
            public float[] Performance { get; set; }

            [ColumnName(@"Result [Training Tag]")]
            public uint Result__Training_Tag_ { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TrainingsML.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
