// <auto-generated />
using Alliance_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alliance_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221012161431_MoreFields")]
    partial class MoreFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Alliance_API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CivicClubAffiliation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CivilStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateJoined")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyOfficeContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyRelationship")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyResidentialContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfChildren")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfDependents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionApplied")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvincialAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProvincialContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpouseOccupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
